name: Build and Publish Release

on:
  workflow_dispatch: 

jobs:
  npmRunBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install -g pnpm@8.5.1 shx@0.3.4
          pnpm install

      - name: Build
        run: pnpm run build

      - name: Archive dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  downloadRclone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fix permissions
        run: |
          chmod 777 -R .

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my_backend_image ./backend
        working-directory: ${{ github.workspace }}

      - name: Run Docker container
        run: |
          docker run -v ${{ github.workspace }}/backend:/backend my_backend_image
        working-directory: ${{ github.workspace }}

      - name: Archive rclone folder
        uses: actions/upload-artifact@v2
        with:
          name: rclone
          path: backend/out/rclone

  prepareFolders:
    runs-on: ubuntu-latest
    needs: [npmRunBuild, downloadRclone]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        
      - name: List folder
        run: |
          ls -lahR

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Prepare folders
        run: |
          mkdir decky-cloud-save decky-cloud-save/bin
          cp -r backend/dist decky-cloud-save/dist
          cp -r defaults/quickstart decky-cloud-save/quickstart 
          cp defaults/rclone decky-cloud-save/rclone
          cp backend/out/rclone decky-cloud-save/bin 
          cp decky_plugin.pyi decky-cloud-save/decky_plugin.pyi
          cp LICENSE decky-cloud-save/LICENSE
          cp main.py decky-cloud-save/main.py
          cp package.json decky-cloud-save/package.json
          cp plugin.json decky-cloud-save/plugin.json
          cp README.md decky-cloud-save/README.md
          zip -r decky-cloud-save.zip decky-cloud-save

      - name: Archive zip file
        uses: actions/upload-artifact@v2
        with:
          name: decky-cloud-save
          path: decky-cloud-save.zip